services:
  pathway_app:
    build: .
    container_name: pathway_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    env_file:
      - .env
    command: ["python", "-m", "app.main"]
