# render.yaml
services:
  - type: web
    name: rag-pathway-app
    env: docker
    plan: starter        # free / small instance
    dockerfilePath: Dockerfile
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1     # we already CMD in Dockerfile, no override
    buildCommand: ""     # no extra build step
    port: 8000           # match EXPOSE
    # bump memory if you find 512Mi too small
    resources:
      memoryGb: 1
    envVars:
      - key: SUPABASE_URL
        sync: true
      - key: SUPABASE_KEY
        sync: true
      - key: SUPABASE_BUCKET
        sync: true
      - key: SUPABASE_DB
      - key: SUPABASE_USER
      - key: SUPABASE_PASSWORD
      - key: SUPABASE_HOST
      - key: SUPABASE_PORT
      - key: HF_API_TOKEN
        sync: true
